### ISSUE TITLE
Attempting to run synthetic.py

### ISSUE THREAD

**Issue by AdamBanham** [niklasadams/explainable_concept_drift_pm#1]
Hello, 

I am part of the reading group at QUT, Brisbane, Australia and we have recently read your paper 'A Framework for Explainable concept Drift Detection in Process Mining' from BPM2021. 

I am attempting to re-run your synthetic.py script and have run into an error. The following snippet shows the command output from this script.

> parsing log, completed traces :: 100%|██████████████████████████████████| 14999/14999 [00:04<00:00, 3713.49it/s]
> 285
> (285, 64)
> Original features:  (285, 64)
> Reduced features shape:  (285, 63)
> [133]
> 285
> (285, 42)
> Original features:  (285, 42)
> Reduced features shape:  (285, 32)
> [132]
> Traceback (most recent call last):
>   File "synthetic.py", line 41, in <module>
>     main()
>   File "synthetic.py", line 35, in main
>     p_value = 0.0000000000001)
>   File "...\explainable_concept_drift_pm\pm4py\statistics\time_series\cause_effect.py", line 50, in granger_causality
>     gc_res = grangercausalitytests(granger_data, [k], verbose = False)
>   File "...\\.virtualenvs\explainable_concept_drift_pm-k_vSqhip\lib\site-packages\statsmodels\tsa\stattools.py", line 1494, in grangercausalitytests
>     "The x values include a column with constant values and so"
> statsmodels.tools.sm_exceptions.InfeasibleTestError: The x values include a column with constant values and so the test statistic cannot be computed.

I am running your script in a virtual environment (venv) using Pipenv (a pretty cool package for ensuring the same environment for all users). I have installed all packages in your requirements.txt. The venv is using python 3.7.

Can you advise me on how to proceed?

**Comment by niklasadams** [comment]
Hi Adam, 
I reproduced your error message, it is due to a recent update in statsmodels. I update the requirements.py such that statsmodel 0.12.1 is used, for this it still works, for 0.13.0 it doesn't. So just switch your statsmodels to 0.12.1.
Best regards
Niklas

**Comment by AdamBanham** [comment]
Hi Niklas,

Thanks for the update and clarification. 

I was able to run synthetic.py to produce an outcome. See below, can you confirm this is the intended outcome?
![image](https://user-images.githubusercontent.com/38652037/139524932-131004a4-ce0d-4abe-8114-d8c3b3f2c792.png)

I was also able to run bpi_2017.py. Can you confirm the following outcome?
![image](https://user-images.githubusercontent.com/38652037/139525215-4d96886d-2b6c-47da-a470-512fc4b9721c.png)

Cheers,
Adam
